package com.exceptionteam17.bestcookingconverter.model;

import java.util.TreeMap;

public final class Database {
    public static TreeMap<String, Double> ingredients;

    static {
        ingredients = new TreeMap<>();
        ////////////////////////////////
        ingredients.put(" Cocoa powder", 110.0);
        ingredients.put(" Flour (wheat)", 125.0);
        ingredients.put(" Salt", 240.0);
        ingredients.put(" Sugar (white cristal)", 240.0);
        ingredients.put(" Sugar (powdered)", 130.0);
        ingredients.put(" Rice (uncooked)", 210.0);
        ingredients.put(" Milk (whole)", 260.0);
        ingredients.put(" Oil (vegetable)", 210.0);
        ingredients.put(" Sour cream", 230.0);
        ///////////////////////////////
        ingredients.put("Allspice", 100.0);
        ingredients.put("Almond (butter)", 250.0);
        ingredients.put("Almonds (ground)", 95.0);
        ingredients.put("Almonds (flakes)", 92.0);
        ingredients.put("Almonds (whole)", 170.0);
        ingredients.put("Amaranth (flakes)", 38.0);
        ingredients.put("Amaranth (uncooked)", 193.0);
        ingredients.put("Anchovies", 240.0);
        ingredients.put("Apples (dehydrated)", 60.0);
        ingredients.put("Apples (dried)", 90.0);
        ingredients.put("Apples (sliced)", 180.0);
        ingredients.put("Applesauce (canned)", 245.0);
        ingredients.put("Apricots (dehydrated)", 119.0);
        ingredients.put("Apricots (dried)", 150.0);
        ingredients.put("Arrowroot", 225.0);
        ingredients.put("Artichokes", 168.0);
        ingredients.put("Arugula (raw)", 20.0);
        ingredients.put("Asparagus (canned)", 242.0);
        ingredients.put("Asparagus (raw)", 134.0);
        ingredients.put("Bacon", 180.0);
        ingredients.put("Bake crumbs (fresh)", 90.0);
        ingredients.put("Baking powder",  180.0);
        ingredients.put("Baking soda", 205.0);
        ingredients.put("Bamboo shoots", 270.0);
        ingredients.put("Bananas (dehydrated)", 100.0);
        ingredients.put("Bananas (mashed)", 230.0);
        ingredients.put("Bananas (powder)", 100.0);
        ingredients.put("Bananas (sliced)", 180.0);
        ingredients.put("Barley (uncooked)", 185.0);
        ingredients.put("Basil (dried)", 25.0);
        ingredients.put("Beans (dried)", 200.0);
        ingredients.put("Beef (cooked)", 230.0);
        ingredients.put("Beef (raw)", 220.0);
        ingredients.put("Beets (canned)", 246.0);
        ingredients.put("Beets (raw)", 136.0);
        ingredients.put("Biscuit mix (Bisquick)", 130.0);
        ingredients.put("Blackberries (raw)", 144.0);
        ingredients.put("Blue corn meal", 120.0);
        ingredients.put("Blueberries (raw)", 150.0);
        ingredients.put("Bran (unsifted)", 55.0);
        ingredients.put("Brazil nuts (whole)", 150.0);
        ingredients.put("Bread crumbs (fresh)", 60.0);
        ingredients.put("Bread crumbs (packaged)", 120.0);
        ingredients.put("Breadfruit (raw)", 220.0);
        ingredients.put("Brussels sprouts (raw)", 88.0);
        ingredients.put("Buckwheat groats", 170.0);
        ingredients.put("Bulgur (cooked)", 182.0);
        ingredients.put("Bulgur (dry)", 140.0);
        ingredients.put("Butter", 230.0);
        ingredients.put("Butter (whipped)", 150.0);
        ingredients.put("Butterbur (raw)", 94.0);
        ingredients.put("Babbage (shredded)", 340.0);
        ingredients.put("Candied lemon peel", 135.0);
        ingredients.put("Candied orange peel", 125.0);
        ingredients.put("Candies (M&M's average)", 200.0);
        ingredients.put("Cashews (oil roasted)", 110.0);
        ingredients.put("Cauliflower fleurets", 230.0);
        ingredients.put("Cereal (Rice Krispies)", 22.0);
        ingredients.put("Carrot (dehydrated)", 74.0);
        ingredients.put("Cassava (raw)", 206.0);
        ingredients.put("Celery seed", 120.0);
        ingredients.put("Cheese (cheddar, grated)", 120.0);
        ingredients.put("Cheese (colby, grated)", 110.0);
        ingredients.put("Cheese (cottage)", 260.0);
        ingredients.put("Cheese (cream)", 240.0);
        ingredients.put("Cheese (grated parmesan)", 180.0);
        ingredients.put("Cheese (jack, grated)", 130.0);
        ingredients.put("Cheese (limburger)", 134.0);
        ingredients.put("Cheese (parmesan grated)", 100.0);
        ingredients.put("Cheese (ricotta)", 248.0);
        ingredients.put("Chickpeas", 190.0);
        ingredients.put("Chives (chopped dried)", 8.0);
        ingredients.put("Chives (chopped fresh)", 50.0);
        ingredients.put("Chocolate chips", 180.0);
        ingredients.put("Chocolate (grated)", 100.0);
        ingredients.put("Chocolate (melted)", 240.0);
        ingredients.put("Cinnamon (ground)", 120.0);
        ingredients.put("Cloves (ground)", 95.0);
        ingredients.put("Cloves (whole)", 90.0);
        ingredients.put("Cocoa powder", 110.0);
        ingredients.put("Coconut (shredded)", 75.0);
        ingredients.put("Coconut flour", 94.0);
        ingredients.put("Coffee (ground)", 90.0);
        ingredients.put("Coffee (instant)", 55.0);
        ingredients.put("Coriander (raw leafs)", 16.0);
        ingredients.put("Cornmeal", 170.0);
        ingredients.put("Cornstarch (cornflour)", 150.0);
        ingredients.put("Cracker crumbs", 60.0);
        ingredients.put("Cranberries", 100.0);
        ingredients.put("Cream of tartar", 150.0);
        ingredients.put("Cream of wheat", 180.0);
        ingredients.put("Cress (raw)", 50.0);
        ingredients.put("Crisco (melted)", 210.0);
        ingredients.put("Crisco (solid)", 220.0);
        ingredients.put("Currants", 150.0);
        ingredients.put("Dates (chopped)", 150.0);
        ingredients.put("Egg noodles", 90.0);
        ingredients.put("Egg whites", 220.0);
        ingredients.put("Egg yolks", 270.0);
        ingredients.put("Eggs (beaten)", 230.0);
        ingredients.put("Elderberries (raw)", 145.0);
        ingredients.put("Evaporated milk", 220.0);
        ingredients.put("Farina", 180.0);
        ingredients.put("Figs (dried)", 165.0);
        ingredients.put("Fish oil", 218.0);
        ingredients.put("Flour (Deaf Smith)", 130.0);
        ingredients.put("Flour (U.K. self-raising)", 110.0);
        ingredients.put("Flour (U.S. all-purpose)", 100.0);
        ingredients.put("Flour (arrowroot)", 128.0);
        ingredients.put("Flour (barley)", 148.0);
        ingredients.put("Flour (buckwheat)", 170.0);
        ingredients.put("Flour (buckwheat whole-groat)", 120.0);
        ingredients.put("Flour (coconut)", 94.0);
        ingredients.put("Flour (cake)", 90.0);
        ingredients.put("Flour (corn)", 161.0);
        ingredients.put("Flour (corn whole-grain)", 117.0);
        ingredients.put("Flour (legume)", 130.0);
        ingredients.put("Flour (potato)", 170.0);
        ingredients.put("Flour (rice)", 150.0);
        ingredients.put("Flour (rye)", 90.0);
        ingredients.put("Flour (semolina)", 175.0);
        ingredients.put("Flour (sorghum)", 121.0);
        ingredients.put("Flour (soy)", 105.0);
        ingredients.put("Flour (wheat)", 125.0);
        ingredients.put("Flour (wheat bread)", 100.0);
        ingredients.put("Flour (whole wheat)", 130.0);
        ingredients.put("Fungus (wood ear)", 100.0);
        ingredients.put("Garlic", 160.0);
        ingredients.put("Garlic (minced)", 150.0);
        ingredients.put("Gelatin", 220.0);
        ingredients.put("Ginger (crystal)", 240.0);
        ingredients.put("Ginger (fresh)", 230.0);
        ingredients.put("Ginger (ground)", 120.0);
        ingredients.put("Graham cracker crumbs", 90.0);
        ingredients.put("Grape nuts", 120.0);
        ingredients.put("Gumdrops", 160.0);
        ingredients.put("Gummi bears", 150.0);
        ingredients.put("Hazelnuts (whole)", 170.0);
        ingredients.put("Honey", 340.0);
        ingredients.put("Hummus", 246.0);
        ingredients.put("Jam", 307.0);
        ingredients.put("Kamut (cooked)", 172.0);
        ingredients.put("Kamut (uncooked)", 186.0);
        ingredients.put("Kasha", 170.0);
        ingredients.put("Ketchup", 270.0);
        ingredients.put("Kohlrabi (raw)", 135.0);
        ingredients.put("Lard", 220.0);
        ingredients.put("Lemon grass (raw)", 67.0);
        ingredients.put("Lemon rind (grated)", 150.0);
        ingredients.put("Lentils", 200.0);
        ingredients.put("Linseed", 165.0);
        ingredients.put("Macaroni (uncooked)", 115.0);
        ingredients.put("Margarine", 220.0);
        ingredients.put("Marshmallows (small)", 50.0);
        ingredients.put("Mashed potatoes", 210.0);
        ingredients.put("Mayonnaise", 220.0);
        ingredients.put("Milk (whole)", 260.0);
        ingredients.put("Milk (evaporated)", 220.0);
        ingredients.put("Milk (powdered)", 115.0);
        ingredients.put("Millet (raw)", 200.0);
        ingredients.put("Molasses", 350.0);
        ingredients.put("Mushrooms (Chinese black)", 50.0);
        ingredients.put("Mushrooms (chopped)", 75.0);
        ingredients.put("Mushrooms (sliced)", 65.0);
        ingredients.put("Mushrooms (whole)", 60.0);
        ingredients.put("Mustard seed", 150.0);
        ingredients.put("Mustard (dry)", 115.0);
        ingredients.put("Mustard (prepared)", 250.0);
        ingredients.put("Oatmeal (uncooked)", 80.0);
        ingredients.put("Oats (rolled)", 80.0);
        ingredients.put("Oats (steel-cut)", 160.0);
        ingredients.put("Oil (vegetable)", 210.0);
        ingredients.put("Okra (raw)", 100.0);
        ingredients.put("Olive oil", 190.0);
        ingredients.put("Olives (chopped)", 180.0);
        ingredients.put("Onion (chopped)", 150.0);
        ingredients.put("Onion (minced)", 200.0);
        ingredients.put("Onion (sliced)", 130.0);
        ingredients.put("Orange rind (grated)", 90.0);
        ingredients.put("Oreo cookies (crushed)", 120.0);
        ingredients.put("Paprika", 115.0);
        ingredients.put("Parsley (fresh)", 40.0);
        ingredients.put("Pasta (egg noodles)", 90.0);
        ingredients.put("Pasta (macaroni)", 115.0);
        ingredients.put("Peanut butter", 180.0);
        ingredients.put("Peanuts (chopped)", 160.0);
        ingredients.put("Peanuts (oil roasted)", 150.0);
        ingredients.put("Peas (uncooked)", 150.0);
        ingredients.put("Pecans (chopped)", 120.0);
        ingredients.put("Pecans (ground)", 100.0);
        ingredients.put("Pecans (shelled)", 120.0);
        ingredients.put("Peppercorns (black)", 135.0);
        ingredients.put("Peppercorns (white)", 150.0);
        ingredients.put("Peppers (chopped chili)", 170.0);
        ingredients.put("Pignoli / pine nuts", 125.0);
        ingredients.put("Plums (raw)", 161.0);
        ingredients.put("Poppy seeds", 135.0);
        ingredients.put("Potatoes (cooked diced)", 200.0);
        ingredients.put("Potatoes (mashed)", 210.0);
        ingredients.put("Potatoes (sliced raw)", 180.0);
        ingredients.put("Pumpkin (cooked)", 180.0);
        ingredients.put("Pumpkin seeds", 134.0);
        ingredients.put("Quinoa", 190.0);
        ingredients.put("Raisins", 150.0);
        ingredients.put("Raspberries (raw)", 123.0);
        ingredients.put("Rice (steamed)", 160.0);
        ingredients.put("Rice (uncooked)", 210.0);
        ingredients.put("Rice (uncooked Basmati)", 195.0);
        ingredients.put("Rice (wild)", 145.0);
        ingredients.put("Salt", 240.0);
        ingredients.put("Scallions / green onions", 50.0);
        ingredients.put("Sesame seeds", 160.0);
        ingredients.put("Shallots", 240.0);
        ingredients.put("Sour cream", 230.0);
        ingredients.put("Soy milk", 243.0);
        ingredients.put("Spaghetti (uncooked)", 120.0);
        ingredients.put("Spinach (cooked)", 180.0);
        ingredients.put("Spinach (raw)", 30.0);
        ingredients.put("Split peas", 200.0);
        ingredients.put("Strawberries", 150.0);
        ingredients.put("Sugar (brown)", 200.0);
        ingredients.put("Sugar (white cristal)", 240.0);
        ingredients.put("Sugar (castor)", 190.0);
        ingredients.put("Sugar (confectioner)", 130.0);
        ingredients.put("Sugar (granulated)", 190.0);
        ingredients.put("Sugar (powdered)", 130.0);
        ingredients.put("Sultanas", 150.0);
        ingredients.put("Sunflower seeds", 146.0);
        ingredients.put("Sweet potatoes (cooked)", 240.0);
        ingredients.put("Sweet potatoes (raw)", 180.0);
        ingredients.put("Syrup (corn)", 350.0);
        ingredients.put("Tea", 75.0);
        ingredients.put("Tiger lily blossoms", 40.0);
        ingredients.put("Tofu (raw)", 250.0);
        ingredients.put("Tomatoes (chopped)", 160.0);
        ingredients.put("Tomatoes (pasta canned)", 260.0);
        ingredients.put("Tuna (canned)", 200.0);
        ingredients.put("Turmeric (ground)", 140.0);
        ingredients.put("Vanilla extract", 208.0);
        ingredients.put("Vanilla wafers (crushed)", 160.0);
        ingredients.put("Vinegar", 248.0);
        ingredients.put("Walnuts (chopped)", 115.0);
        ingredients.put("Walnuts (ground)", 85.0);
        ingredients.put("Walnuts (shelled)", 120.0);
        ingredients.put("Water", 236.59);
        ingredients.put("Wheat germ", 125.0);
        ingredients.put("Wild rice", 145.0);
        ingredients.put("Wine", 248.0);
        ingredients.put("Whip cream", 60.0);
        ingredients.put("Yeast (active dry)", 290.0);
    }
}
